wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
    start_time: 1649473078
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      4: 3.7.6
      5: 0.12.14
      8:
      - 5
alpha:
  desc: null
  value: 1.0
beta:
  desc: null
  value: 0.8
dataset:
  desc: null
  value: cora
ep_epochs:
  desc: null
  value: 160
feat_norm:
  desc: null
  value: row
gnn:
  desc: null
  value: gcn
layer_type:
  desc: null
  value: gcn
lr:
  desc: null
  value: 0.01
n_layers:
  desc: null
  value: 1
nc_epochs:
  desc: null
  value: 30
temperature:
  desc: null
  value: 1.2
warmup:
  desc: null
  value: 0
